### ISSUE TITLE
Please add an explicit Open Source Software license

### ISSUE THREAD

**Issue by beckettsean** [cloudfoundry/packit#6]
Howdy! There are some commercial products that want to package this repo, but cannot until there is an explicit license. It's legally dangerous for anyone to use your code without some form of license on the code. Most CF projects are Apache 2 licensed. 

Thanks!

**Comment by kvedurmu** [comment]
Hey @beckettsean. This was done as a part of https://github.com/cloudfoundry/packit/commit/7fa922672818e24a62996576207cef0dc824f0d4. Closing this

**Comment by beckettsean** [comment]
Wonderful, thanks for the very rapid turnaround!
